config/routes.rb
Odot::Application.routes.draw do

  resources :todo_lists do
	resources :todo_items
  end
  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
  					  length: { minimum: 3 }

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items

	validates :name, presence: true
	validates :name, length: { minimum: 3 }

	validates :description, presence: true
	validates :description, length: {  minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list
  
  def index
  end

  def new
	@todo_item = @todo_list.todo_items.new
  end

  def create
	@todo_item = @todo_list.todo_items.new(todo_item_params)
	if @todo_item.save
	  flash[:success] = "Added todo list item."
	  redirect_to todo_list_todo_items_path
	else
	  flash[:error] = "There was a problem adding that todo_list item."
	  render action: :new
	end
  end

  def edit
	@todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
	@todo_item = @todo_list.todo_items.find(params[:id])
	if @todo_item.update_attributes(todo_item_params)
	  flash[:success] = "Saved todo list item."
	  redirect_to todo_list_todo_items_path
	else
	  flash[:error] = "That todo item could not be saved."
	  render action: :edit
	end
  end

  def destroy
	@todo_item = @todo_list.todo_items.find(params[:id])
	if @todo_item.destroy
	  flash[:success] = "Todo list item was deleted."
	else
	  flash[:error] = "Todo list item could not be deleted."
	end
	redirect_to todo_list_todo_items_path
  end

  def url_options
	{ todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private
  def todo_item_params
	params[:todo_item].permit(:content)
  end

  private
  def find_todo_list
  	@todo_list = TodoList.find(params[:todo_list_id])
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
  <div class="alert flash <%= type %>">
    <%= message %>
  </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

  <ul>
    <% @todo_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form.label :content %>
<%= form.text_field :content %>
<%= form.submit "Save" %>
 

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.name %> - Editing Todo List Item  </h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %> 


 

app/views/todo_items/index.html.erb
<h1><%=@todo_list.name%></h1>

<ul class="todo_items">
	<% @todo_list.todo_items.each do |todo_item| %>
	<li id="<%= dom_id(todo_item) %>"> 
		<%=todo_item.content%> 
		<%=link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
		<%=link_to "Delete", todo_list_todo_item_path(todo_item), 
						method: :delete,
						data: { confirm: "Are you sure?" } %>

	</li>
	<% end %>
</ul>

<p>
	<%= link_to "New Todo Item", new_todo_list_todo_item_path %>
</p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.name %> - Creating Todo List Item  </h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %> 

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing todo_lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr id="<%= dom_id(todo_list) %>">
        <td><%= todo_list.name %></td>
        <td><%= todo_list.description %></td>
        <td>
			<%= link_to "List Items", todo_list_todo_items_path(todo_list) %>
			<%= link_to 'Show', todo_list %>
        	<%= link_to 'Edit', edit_todo_list_path(todo_list) %>
        	<%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>